import sys
import numpy as np
import cv2

try:
    from app.processor import process_image, ProcessingParams
    
    # Create a dummy image 100x100 BGR
    dummy_image = np.zeros((100, 100, 3), dtype=np.uint8)
    success, encoded = cv2.imencode(".jpg", dummy_image)
    raw_bytes = encoded.tobytes()
    
    params = ProcessingParams(
        mode="depth",
        scan_density=50.0,
        noise_level=10.0,
        edge_sensitivity=50.0,
        depth_contrast=50.0,
        smoothing=50.0,
        point_density=50.0
    )
    
    result = process_image(raw_bytes, params)
    print("SUCCESS: Generated bytes length:", len(result))
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(1)
